# Generated by Django 5.1.4 on 2025-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcSqrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='a')),
                ('coeficiente_b', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='b')),
                ('coeficiente_c', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='c')),
            ],
        ),
    ]
